[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx.err

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm.err

[program:laravel-scheduler]
command=php /app/laravel-backend/artisan schedule:work
autostart=true
autorestart=true
stdout_logfile=/var/log/scheduler.log
stderr_logfile=/var/log/scheduler.err

[program:reverb]
command=php /app/laravel-backend/artisan reverb:start --hostname=sonix-production.up.railway.app --host=0.0.0.0 --port=8080
autostart=true
autorestart=true
stdout_logfile=/var/log/reverb.log
stderr_logfile=/var/log/reverb.err
stopwaitsecs=10
